/**
 * Generated by orval v7.17.0 🍺
 * Spited by organize-types.js
 * Do not edit manually.
 */

export * from './userAddressGeo';
export * from './userAddress';
export * from './userCompany';
export * from './user';
export * from './post';
export * from './todo';

// 配列型のエイリアス
import type { User } from './user';
import type { Post } from './post';
import type { Todo } from './todo';

export type Users = User[];
export type Posts = Post[];
export type Todos = Todo[];

// APIエラー型
export type ApiError = {
  message: string;
  status?: number;
  code?: string;
};
