/**
 * Generated by orval v7.17.0 🍺
 * Spited by organize-types.js
 * Do not edit manually.
 */

export interface Post {
  id: number;
  userId: number;
  title: string;
  body: string;
  isNew?: boolean;
  modified?: boolean;
}
