/**
 * Generated by orval v7.17.0 🍺
 * Spited by organize-types.js
 * Do not edit manually.
 */

import type { UserAddress } from './userAddress.g';
import type { UserCompany } from './userCompany.g';

export interface User {
  id: number;
  name: string;
  username: string;
  email: string;
  phone: string;
  website: string;
  address?: UserAddress;
  company?: UserCompany;
  selected?: boolean;
}
