/**
 * Generated by orval v7.17.0 🍺
 * Spited by organize-types.js
 * Do not edit manually.
 */

export * from './userAddressGeo.g';
export * from './userAddress.g';
export * from './userCompany.g';
export * from './user.g';
export * from './post.g';
export * from './todo.g';

// 配列型のエイリアス
import type { User } from './user.g';
import type { Post } from './post.g';
import type { Todo } from './todo.g';

export type Users = User[];
export type Posts = Post[];
export type Todos = Todo[];

// APIエラー型
export type ApiError = {
  message: string;
  status?: number;
  code?: string;
};
