/**
 * Generated by orval v7.17.0 🍺
 * Spited by organize-types.js
 * Do not edit manually.
 */

import type { UserAddressGeo } from './userAddressGeo.g';

export type UserAddress = {
  street?: string;
  suite?: string;
  city?: string;
  zipcode?: string;
  geo?: UserAddressGeo;
}
