// Generated by ts-to-zod
import { z } from "zod";

export const postSchema = z.object({
    id: z.number(),
    userId: z.number(),
    title: z.string(),
    body: z.string(),
    isNew: z.boolean().optional(),
    modified: z.boolean().optional()
});

export const postsSchema = z.array(postSchema);
