// Generated by ts-to-zod
import { z } from "zod";

export const todoSchema = z.object({
    id: z.number(),
    userId: z.number(),
    title: z.string(),
    completed: z.boolean()
});

export const todosSchema = z.array(todoSchema);
