// Generated by ts-to-zod
import { z } from "zod";

export const userSchema = z.object({
    id: z.number(),
    name: z.string(),
    username: z.string(),
    email: z.string(),
    phone: z.string(),
    website: z.string(),
    address: z.object({
        street: z.string(),
        suite: z.string(),
        city: z.string(),
        zipcode: z.string(),
        geo: z.object({
            lat: z.string(),
            lng: z.string()
        })
    }).optional(),
    company: z.object({
        name: z.string(),
        catchPhrase: z.string(),
        bs: z.string()
    }).optional(),
    selected: z.boolean().optional()
});

export const usersSchema = z.array(userSchema);
