openapi: 3.0.3
info:
  title: React Native Tutorial API
  version: 1.0.0
  description: React Native チュートリアルアプリのAPI仕様

servers:
  - url: https://api.example.com
    description: Production server
  - url: http://localhost:3000
    description: Development server (MSW)

# =============================================================================
# パス定義（外部ファイル参照）
# =============================================================================
paths:
  # Users
  /users:
    $ref: './paths/users.yaml#/~1users'
  /users/{id}:
    $ref: './paths/users.yaml#/~1users~1{id}'
  
  # Posts
  /posts:
    $ref: './paths/posts.yaml#/~1posts'
  /posts/{id}:
    $ref: './paths/posts.yaml#/~1posts~1{id}'
  
  # Todos
  /todos:
    $ref: './paths/todos.yaml#/~1todos'
  /todos/{id}:
    $ref: './paths/todos.yaml#/~1todos~1{id}'

# =============================================================================
# スキーマ定義（外部ファイル参照）
# orvalはこの部分をもとに型定義を生成
# =============================================================================
components:
  schemas:
    # 共通型 (schemas/common に定義)
    # ※「Request」「Response」を名前に含めないこと
    User:
      $ref: './schemas/common.yaml#/User'
    Post:
      $ref: './schemas/common.yaml#/Post'
    Todo:
      $ref: './schemas/common.yaml#/Todo'

    # リクエスト型 (schemas/requests に定義)
    # ※「Request」を名前に含めること
    CreateUserRequest:
      $ref: './schemas/requests.yaml#/CreateUserRequest'
    UpdateUserRequest:
      $ref: './schemas/requests.yaml#/UpdateUserRequest'
    CreatePostRequest:
      $ref: './schemas/requests.yaml#/CreatePostRequest'
    UpdatePostRequest:
      $ref: './schemas/requests.yaml#/UpdatePostRequest'
    CreateTodoRequest:
      $ref: './schemas/requests.yaml#/CreateTodoRequest'
    UpdateTodoRequest:
      $ref: './schemas/requests.yaml#/UpdateTodoRequest'

    # レスポンス型 (schemas/responses に定義)
    # ※「Response」を名前に含めること
    GetUsersResponse:
      $ref: './schemas/responses.yaml#/GetUsersResponse'
    GetUserResponse:
      $ref: './schemas/responses.yaml#/GetUserResponse'
    CreateUserResponse:
      $ref: './schemas/responses.yaml#/CreateUserResponse'
    UpdateUserResponse:
      $ref: './schemas/responses.yaml#/UpdateUserResponse'
    GetPostsResponse:
      $ref: './schemas/responses.yaml#/GetPostsResponse'
    GetPostResponse:
      $ref: './schemas/responses.yaml#/GetPostResponse'
    CreatePostResponse:
      $ref: './schemas/responses.yaml#/CreatePostResponse'
    UpdatePostResponse:
      $ref: './schemas/responses.yaml#/UpdatePostResponse'
    GetTodosResponse:
      $ref: './schemas/responses.yaml#/GetTodosResponse'
    GetTodoResponse:
      $ref: './schemas/responses.yaml#/GetTodoResponse'
    CreateTodoResponse:
      $ref: './schemas/responses.yaml#/CreateTodoResponse'
    UpdateTodoResponse:
      $ref: './schemas/responses.yaml#/UpdateTodoResponse'
