#!/usr/bin/env node

/**
 * Orvalで生成された単一ファイルを
 * common/requests/responsesフォルダに分割する
 * 
 * ルール:
 * - *Request → requests/
 * - *Response → responses/
 * - それ以外（エンティティ型） → common/
 */

const fs = require('fs');
const path = require('path');

const sourceFile = './src/model/genTypes/reactNativeTutorialAPI.g.ts';
const baseDir = './src/model/genTypes';

// ディレクトリ作成
const dirs = ['common', 'requests', 'responses'];
dirs.forEach(dir => {
  const dirPath = path.join(baseDir, dir);
  if (fs.existsSync(dirPath)) {
    fs.rmSync(dirPath, { recursive: true });
  }
  fs.mkdirSync(dirPath, { recursive: true });
});

// ファイルを読み込み
const content = fs.readFileSync(sourceFile, 'utf8');

// ヘッダーコメント
const header = `/**
 * Generated by orval v7.17.0 🍺
 * Spited by organize-types.js
 * Do not edit manually.
 */
`;

// 全ての型定義を抽出（interface と type の両方）
// 1. interface: export interface Foo { ... }
// 2. type object: export type Foo = { ... }
// 3. type alias: export type Foo = Bar; または export type Foo = Bar[];
const types = [];

// interface と type object を抽出
const objectTypeRegex = /export (?:interface|type) (\w+)\s*(?:=\s*)?{[^}]*}/gs;
let match;
while ((match = objectTypeRegex.exec(content)) !== null) {
  types.push({
    name: match[1],
    definition: match[0]
  });
}

// type alias を抽出 (export type Foo = Bar; または export type Foo = Bar[];)
const typeAliasRegex = /export type (\w+)\s*=\s*([^{][^;]*);/g;
while ((match = typeAliasRegex.exec(content)) !== null) {
  // 既に抽出済みでないか確認
  if (!types.some(t => t.name === match[1])) {
    types.push({
      name: match[1],
      definition: match[0],
      isAlias: true,
      aliasTarget: match[2].trim()
    });
  }
}

// 型を振り分け
const requestTypes = types.filter(t => /Request$/.test(t.name));
const responseTypes = types.filter(t => /Response$/.test(t.name));
const commonTypes = types.filter(t => !/Request$/.test(t.name) && !/Response$/.test(t.name));

// 依存関係を解析して適切なインポートを追加
function getImports(definition, availableTypes, currentTypeName) {
  const imports = [];
  availableTypes.forEach(t => {
    if (t.name !== currentTypeName) {
      // 型定義内で他の型を参照しているかチェック
      const regex = new RegExp(`\\b${t.name}\\b`, 'g');
      if (regex.test(definition)) {
        imports.push(t.name);
      }
    }
  });
  return imports;
}

// ファイル名を生成（PascalCase → camelCase）
function toFileName(typeName) {
  return typeName.charAt(0).toLowerCase() + typeName.slice(1) + '.g.ts';
}

// Common型を個別ファイルに出力（依存関係のインポート付き）
commonTypes.forEach(type => {
  const filename = toFileName(type.name);
  const imports = getImports(type.definition, commonTypes, type.name);
  
  let fileContent = header + '\n';
  if (imports.length > 0) {
    imports.forEach(imp => {
      const impFileName = toFileName(imp).replace('.ts', '');
      fileContent += `import type { ${imp} } from './${impFileName}';\n`;
    });
    fileContent += '\n';
  }
  fileContent += type.definition + '\n';
  
  fs.writeFileSync(path.join(baseDir, 'common', filename), fileContent);
});

// Request型を個別ファイルに出力
requestTypes.forEach(type => {
  const filename = toFileName(type.name);
  const fileContent = header + '\n' + type.definition + '\n';
  fs.writeFileSync(path.join(baseDir, 'requests', filename), fileContent);
});

// Response型を個別ファイルに出力
responseTypes.forEach(type => {
  const filename = toFileName(type.name);
  
  // aliasTargetまたはdefinitionから依存型を取得
  const searchText = type.aliasTarget || type.definition;
  const imports = getImports(searchText, [...commonTypes, ...responseTypes], type.name);
  
  let fileContent = header + '\n';
  if (imports.length > 0) {
    imports.forEach(imp => {
      // commonにあるかresponsesにあるか判定
      const isCommon = commonTypes.some(t => t.name === imp);
      const impFileName = toFileName(imp).replace('.g.ts', '');
      const importPath = isCommon ? `../common/${impFileName}.g` : `./${impFileName}.g`;
      fileContent += `import type { ${imp} } from '${importPath}';\n`;
    });
    fileContent += '\n';
  }
  fileContent += type.definition + '\n';
  
  fs.writeFileSync(path.join(baseDir, 'responses', filename), fileContent);
});

// common/index.ts（配列型のエイリアスも含む）
let commonIndex = header + '\n' +
  commonTypes.map(t => `export * from './${toFileName(t.name).replace('.g.ts', '.g')}';`).join('\n') + '\n\n';

// 配列型のエイリアスを追加（エンティティ型のみ）
const entityTypes = commonTypes.filter(t => 
  !t.name.includes('Address') && !t.name.includes('Company') && !t.name.includes('Geo')
);
if (entityTypes.length > 0) {
  commonIndex += '// 配列型のエイリアス\n';
  entityTypes.forEach(t => {
    commonIndex += `import type { ${t.name} } from './${toFileName(t.name).replace('.g.ts', '.g')}';\n`;
  });
  commonIndex += '\n';
  entityTypes.forEach(t => {
    commonIndex += `export type ${t.name}s = ${t.name}[];\n`;
  });
  commonIndex += '\n';
}

// APIエラー型を追加
commonIndex += `// APIエラー型
export type ApiError = {
  message: string;
  status?: number;
  code?: string;
};
`;

fs.writeFileSync(path.join(baseDir, 'common', 'index.ts'), commonIndex);

// requests/index.ts
const requestsIndex = header + '\n' +
  requestTypes.map(t => `export * from './${toFileName(t.name).replace('.g.ts', '.g')}';`).join('\n') + '\n';
fs.writeFileSync(path.join(baseDir, 'requests', 'index.ts'), requestsIndex);

// responses/index.ts（commonからのre-exportも含む）
let responsesIndex = header + '\n';
// commonからre-export
// responsesIndex += '// commonからのre-export（エンティティ型）\n';
// responsesIndex += `export * from '../common';\n\n`;
// Response型
if (responseTypes.length > 0) {
  responsesIndex += '// Response型\n';
  responsesIndex += responseTypes.map(t => `export * from './${toFileName(t.name).replace('.g.ts', '.g')}';`).join('\n') + '\n';
}
fs.writeFileSync(path.join(baseDir, 'responses', 'index.ts'), responsesIndex);

// メインindex.ts
const mainIndex = `${header}
// 共通型（エンティティ）
export * from './common';

// リクエスト型
export * from './requests';

// レスポンス型
export * from './responses';
`;
fs.writeFileSync(path.join(baseDir, 'index.ts'), mainIndex);

// 元のファイルを削除
fs.unlinkSync(sourceFile);

console.log('✅ 型定義をフォルダ分けしました:');
console.log(`  - common/: ${commonTypes.length}ファイル（エンティティ型）`);
console.log(`  - requests/: ${requestTypes.length}ファイル`);
console.log(`  - responses/: ${responseTypes.length}ファイル`);
console.log('');
console.log('Common型:', commonTypes.map(t => t.name).join(', '));
console.log('Request型:', requestTypes.map(t => t.name).join(', '));
console.log('Response型:', responseTypes.map(t => t.name).join(', ') || '(なし)');


