/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";

export const sampleTypeSchema = z.object({
    id: z.number(),
    address: z.string()
});
