/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from 'zod';
import { todoSchema } from "../common/todo.g";


export const updateTodoResponseSchema = todoSchema;
