/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";

export const createPostRequestSchema = z.object({
    userId: z.number(),
    title: z.string(),
    body: z.string()
});
