/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from 'zod';
import { userAddressGeoSchema } from "./userAddressGeo.g";


export const userAddressSchema = z.object({
  street: z.string().optional(),
  suite: z.string().optional(),
  city: z.string().optional(),
  zipcode: z.string().optional(),
  geo: userAddressGeoSchema.optional(),
});
