/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";
import { userAddressSchema } from "./userAddress.g";
import { userCompanySchema } from "./userCompany.g";



export const userSchema = z.object({
  id: z.number(),
  name: z.string(),
  username: z.string(),
  email: z.string(),
  phone: z.string(),
  website: z.string(),
  address: userAddressSchema.optional(),
  company: userCompanySchema.optional(),
  selected: z.boolean().optional(),
});
