/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";
import { postSchema } from "../common/post";


export const getPostResponseSchema = postSchema;
