/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";
import { userSchema } from "../common/user.g";


export const getUserResponseSchema = userSchema;
