/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */

// 配列型とAPIエラーのZodスキーマ
import { z } from "zod";
import { postSchema } from "./post.g";
import { todoSchema } from "./todo.g";
import { userSchema } from "./user.g";

export const postsSchema = z.array(postSchema);
export const todosSchema = z.array(todoSchema);
export const usersSchema = z.array(userSchema);

export const apiErrorSchema = z.object({
  message: z.string(),
  status: z.number().optional(),
  code: z.string().optional()
});
