/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";

export const postSchema = z.object({
    id: z.number(),
    userId: z.number(),
    title: z.string(),
    body: z.string(),
    isNew: z.boolean().optional(),
    modified: z.boolean().optional()
});
