/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";

export const userAddressGeoSchema = z.object({
    lat: z.string().optional(),
    lng: z.string().optional()
});
