/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";

export const userCompanySchema = z.object({
    name: z.string().optional(),
    catchPhrase: z.string().optional(),
    bs: z.string().optional()
});
