/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";

export const createTodoRequestSchema = z.object({
  userId: z.number(),
  title: z.string(),
  completed: z.boolean().optional(),
});
