/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from 'zod';

export const createUserRequestSchema = z.object({
  name: z.string(),
  username: z.string(),
  email: z.string(),
  phone: z.string().optional(),
  website: z.string().optional(),
});
