/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from 'zod';

export const updatePostRequestSchema = z.object({
  title: z.string().optional(),
  body: z.string().optional(),
});
