/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from "zod";

export const updateTodoRequestSchema = z.object({
  title: z.string().optional(),
  completed: z.boolean().optional(),
});
