#!/usr/bin/env node

/**
 * common/, requests/, responses/ フォルダ内の型ファイルからZodスキーマを生成
 * 
 * 処理方針:
 * - すべての型ファイルに対してts-to-zodを使用（並列処理で高速化）
 * - ts-to-zodがz.any()を出力した場合、適切なスキーマインポートに置換
 * 
 * 出力先:
 * - model/schemas/common/ ← common/の型から生成（エンティティ）
 * - model/schemas/requests/ ← requests/の型から生成
 * - model/schemas/responses/ ← responses/の型から生成
 */

const { execSync, exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const { promisify } = require('util');
const execAsync = promisify(exec);

const baseTypesDir = './model/genTypes';
const baseSchemasDir = './model/schemas';

// ts-to-zodのパス（npxを使わず直接実行して高速化）
const tsToZodBin = path.resolve(__dirname, '../node_modules/.bin/ts-to-zod');

// 生成ファイル用のヘッダーコメント
const generatedHeader = `/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
`;

// schemasディレクトリをクリーンアップ
if (fs.existsSync(baseSchemasDir)) {
  fs.rmSync(baseSchemasDir, { recursive: true });
}

// サブディレクトリを作成
['common', 'requests', 'responses'].forEach(dir => {
  fs.mkdirSync(path.join(baseSchemasDir, dir), { recursive: true });
});

console.log('🔄 Zodスキーマを生成中...\n');

/**
 * 型名からファイル名を生成
 * 例: User → user, GetUserResponse → getUserResponse
 */
function toFileName(typeName) {
  return typeName.charAt(0).toLowerCase() + typeName.slice(1);
}

/**
 * 参照先の型がどのフォルダにあるか判定
 */
function findEntityFolder(entityName) {
  const folders = ['common', 'requests', 'responses'];
  for (const folder of folders) {
    const filePath = path.join(baseTypesDir, folder, toFileName(entityName) + '.ts');
    if (fs.existsSync(filePath)) {
      return folder;
    }
  }
  return 'common'; // デフォルト
}

/**
 * スキーマ名から型名を推測
 * 例: userAddressSchema → UserAddress
 */
function schemaNameToTypeName(schemaName) {
  const name = schemaName.replace('Schema', '');
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/**
 * ts-to-zodが生成したz.any()を適切なスキーマ参照に置換
 */
function fixNestedTypes(content, currentFolder) {
  const lines = content.split('\n');
  const fixedLines = [];
  const imports = new Set();
  const localSchemaRemovals = new Set(); // 削除するローカルスキーマ定義
  
  // まず、z.any()で定義されているローカルスキーマを検出
  for (const line of lines) {
    // const xxxSchema = z.any(); パターンを検出
    const localAnyMatch = line.match(/const (\w+Schema) = z\.any\(\);/);
    if (localAnyMatch) {
      const schemaName = localAnyMatch[1];
      const typeName = schemaNameToTypeName(schemaName);
      const folder = findEntityFolder(typeName);
      const fileName = toFileName(typeName);
      
      // 同じフォルダ内に対応する型ファイルがあるかチェック
      const typeFilePath = path.join(baseTypesDir, folder, fileName + '.ts');
      if (fs.existsSync(typeFilePath)) {
        localSchemaRemovals.add(schemaName);
        const relativePath = currentFolder === folder 
          ? './' + fileName
          : '../' + folder + '/' + fileName;
        imports.add('import { ' + schemaName + ' } from "' + relativePath + '";');
      }
    }
  }
  
  // 行を処理
  for (const line of lines) {
    // ローカルスキーマ定義を削除（インポートに置換済み）
    const localAnyMatch = line.match(/const (\w+Schema) = z\.any\(\);/);
    if (localAnyMatch && localSchemaRemovals.has(localAnyMatch[1])) {
      continue; // この行をスキップ
    }
    
    fixedLines.push(line);
  }
  
  // インポート文を追加
  if (imports.size > 0) {
    const importSection = Array.from(imports).join('\n');
    const zodImportIndex = fixedLines.findIndex(l => l.includes('import { z }'));
    if (zodImportIndex !== -1) {
      fixedLines.splice(zodImportIndex + 1, 0, importSection);
    }
  }
  
  return fixedLines.join('\n');
}

/**
 * 型ファイルからZodスキーマを生成（非同期版・並列処理用）
 * 
 * 処理フロー:
 * 1. ts-to-zodでスキーマ生成
 * 2. ヘッダーコメントを置換
 * 3. z.any()があればfixNestedTypesで修正（インポートに置換）
 */
async function generateSchemaForFile(inputPath, outputPath, currentFolder) {
  try {
    // ts-to-zodでスキーマ生成（非同期で並列実行）
    await execAsync(`"${tsToZodBin}" ${inputPath} ${outputPath}`);
    
    // 生成されたファイルを読み込み
    let generatedContent = fs.readFileSync(outputPath, 'utf8');
    
    // ts-to-zodのヘッダーコメントをカスタムヘッダーに置換
    generatedContent = generatedContent.replace(
      /^\/\/ Generated by ts-to-zod\n/,
      generatedHeader
    );
    
    // z.any()が含まれているかチェック
    if (generatedContent.includes('z.any()')) {
      // z.any()を適切なインポートに置換
      const fixedContent = fixNestedTypes(generatedContent, currentFolder);
      fs.writeFileSync(outputPath, fixedContent);
      return { success: true, type: 'fixed', file: path.basename(inputPath) };
    }
    
    fs.writeFileSync(outputPath, generatedContent);
    return { success: true, type: 'generated', file: path.basename(inputPath) };
  } catch (error) {
    return { success: false, error: error.message, file: path.basename(inputPath) };
  }
}

/**
 * フォルダ内のファイルを並列処理でスキーマ生成
 */
async function processFolderParallel(folder) {
  const typesDir = path.join(baseTypesDir, folder);
  const schemasDir = path.join(baseSchemasDir, folder);
  
  if (!fs.existsSync(typesDir)) {
    console.log('📁 ' + folder + '/ (スキップ - ディレクトリなし)');
    return;
  }
  
  console.log('📁 ' + folder + '/');
  
  // .tsファイルを取得（index.ts以外）
  const files = fs.readdirSync(typesDir)
    .filter(f => f.endsWith('.ts') && f !== 'index.ts');
  
  if (files.length === 0) {
    console.log('  (ファイルなし)');
    return;
  }
  
  // 全ファイルを並列処理
  const promises = files.map(file => {
    const inputPath = path.join(typesDir, file);
    const outputPath = path.join(schemasDir, file);
    return generateSchemaForFile(inputPath, outputPath, folder);
  });
  
  const results = await Promise.all(promises);
  
  // 結果を表示
  results.forEach(result => {
    if (result.success) {
      console.log('  ✅ ' + result.file);
    } else {
      console.error('  ❌ ' + result.file + ': ' + result.error);
    }
  });
  
  // index.tsを生成
  const schemaFiles = fs.readdirSync(schemasDir)
    .filter(f => f.endsWith('.ts') && f !== 'index.ts');
  
  if (schemaFiles.length > 0) {
    const indexContent = generatedHeader + '\n// ' + folder + 'のZodスキーマ\n' + schemaFiles.map(f => "export * from './" + f.replace('.ts', '') + "';").join('\n') + '\n';
    fs.writeFileSync(path.join(schemasDir, 'index.ts'), indexContent);
  }
}

// ===== メイン処理（非同期） =====
async function main() {
  // 処理順序: common → requests → responses（依存関係を考慮）
  // commonを先に完了させてから他を並列処理
  await processFolderParallel('common');
  
  // requests と responses は並列処理可能
  await Promise.all([
    processFolderParallel('requests'),
    processFolderParallel('responses')
  ]);

  // ===== common用の配列型とAPIエラーのスキーマを追加 =====
  const commonSchemaPath = path.join(baseSchemasDir, 'common');
  const schemaFiles = fs.readdirSync(commonSchemaPath)
    .filter(f => f.endsWith('.ts') && f !== 'index.ts' && f !== 'arrays.ts');

  // 配列型に使うエンティティを動的に判定（Address, Company, Geo を除く）
  const entityFiles = schemaFiles.filter(f => 
    !f.includes('Address') && !f.includes('Company') && !f.includes('Geo') && !f.includes('Error')
  );

  let arraysContent = generatedHeader + '\n// 配列型とAPIエラーのZodスキーマ\nimport { z } from "zod";\n';

  // エンティティスキーマのインポート
  entityFiles.forEach(f => {
    const baseName = f.replace('.ts', '');
    const schemaName = baseName + 'Schema';
    arraysContent += 'import { ' + schemaName + ' } from "./' + baseName + '";\n';
  });

  arraysContent += '\n';

  // 配列スキーマの定義
  entityFiles.forEach(f => {
    const baseName = f.replace('.ts', '');
    const schemaName = baseName + 'Schema';
    const pluralName = baseName + 'sSchema';
    arraysContent += 'export const ' + pluralName + ' = z.array(' + schemaName + ');\n';
  });

  arraysContent += '\nexport const apiErrorSchema = z.object({\n  message: z.string(),\n  status: z.number().optional(),\n  code: z.string().optional()\n});\n';

  fs.writeFileSync(path.join(commonSchemaPath, 'arrays.ts'), arraysContent);
  console.log('\n  ✅ common/arrays.ts (配列型・APIエラー)');

  // メインのindex.tsを生成
  const mainIndexContent = generatedHeader + "\n// Zodスキーマのエクスポート\n\nexport * from './common';\nexport * from './requests';\nexport * from './responses';\n";

  fs.writeFileSync(path.join(baseSchemasDir, 'index.ts'), mainIndexContent);

  console.log('\n✅ Zodスキーマ生成完了!');
  console.log('   common/ → ' + baseSchemasDir + '/common/');
  console.log('   requests/ → ' + baseSchemasDir + '/requests/');
  console.log('   responses/ → ' + baseSchemasDir + '/responses/');
}

// メイン処理を実行
main().catch(err => {
  console.error('エラー:', err);
  process.exit(1);
});
