/**
 * Generated by ts-to-zod
 * Schema generated by generate-schemas.js
 * Do not edit manually.
 */
import { z } from 'zod';

export const sampleFormTypeSchema = z.object({
  id: z.number(),
  age: z.number(),
  address: z.string(),
  email: z.string(),
});
